
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import Navbar from "@/components/navbar/Navbar";
// import { useParams } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next Appi",
  description: "Generated by create next app",
};

// const params = useParams()

const url = process.env.NEXT_PUBLIC_BASE_URL;

const disableNavbar = [
  `${url}/signin`,
  `${url}/signout`,
  `${url}/admin`,
  `${url}/admin/all-product`,
  `${url}/admin/add-product`,
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* {!disableNavbar.includes(pathname) && <Navbar />} */}
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
